name: 💅 Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: 💅 Lint using GraphOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install

      - name: Export schema
        run:
          pdm run strawberry export-schema --schema app.schema > schema.graphql

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check new schema with Apollo Studio
        run: |
          rover graph lint ./schema.graphql GraphQL-Conf-Demo@current
